In [1]:
import pandas as pd

In [2]:
matches = pd.read_csv("matches.csv", index_col=0)

In [3]:
matches.head()

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,...,Match Report,Notes,Sh,SoT,Dist,FK,PK,PKatt,Season,Team
1,2023-08-12,12:30,Premier League,Matchweek 1,Sat,Home,W,2.0,1.0,Nott'ham Forest,...,Match Report,NaN,15.0,7.0,19.1,0.0,0,0,2024,Arsenal
2,2023-08-21,20:00,Premier League,Matchweek 2,Mon,Away,W,1.0,0.0,Crystal Palace,...,Match Report,NaN,13.0,2.0,16.4,0.0,1,1,2024,Arsenal
3,2023-08-26,15:00,Premier League,Matchweek 3,Sat,Home,D,2.0,2.0,Fulham,...,Match Report,NaN,18.0,9.0,13.8,0.0,1,1,2024,Arsenal
4,2023-09-03,16:30,Premier League,Matchweek 4,Sun,Home,W,3.0,1.0,Manchester Utd,...,Match Report,NaN,17.0,5.0,15.0,0.0,0,0,2024,Arsenal
5,2023-09-17,16:30,Premier League,Matchweek 5,Sun,Away,W,1.0,0.0,Everton,...,Match Report,NaN,13.0,4.0,17.4,0.0,0,0,2024,Arsenal

In [4]:
matches.shape

(3710, 27)

In [5]:
38*20*5

3800

In [6]:
matches["Team"].value_counts()

Arsenal                     186
West Ham United             186
Everton                     186
Liverpool                   186
Wolverhampton Wanderers     186
Crystal Palace              186
Aston Villa                 186
Newcastle United            185
Manchester United           185
Manchester City             184
Chelsea                     184
Brighton and Hove Albion    184
Tottenham Hotspur           184
Leicester City              152
Southampton                 152
Burnley                     148
Leeds United                114
Fulham                      110
Sheffield United            110
Bournemouth                 110
Brentford                   110
Watford                      76
Norwich City                 76
Nottingham Forest            72
West Bromwich Albion         38
Luton Town                   34
Name: Team, dtype: int64

In [7]:
matches["Round"].value_counts()

Matchweek 1     100
Matchweek 17    100
Matchweek 33    100
Matchweek 32    100
Matchweek 31    100
Matchweek 30    100
Matchweek 28    100
Matchweek 27    100
Matchweek 25    100
Matchweek 24    100
Matchweek 23    100
Matchweek 22    100
Matchweek 21    100
Matchweek 2     100
Matchweek 19    100
Matchweek 18    100
Matchweek 20    100
Matchweek 16    100
Matchweek 8     100
Matchweek 3     100
Matchweek 4     100
Matchweek 5     100
Matchweek 6     100
Matchweek 15    100
Matchweek 7     100
Matchweek 9     100
Matchweek 10    100
Matchweek 11    100
Matchweek 12    100
Matchweek 13    100
Matchweek 14    100
Matchweek 26     98
Matchweek 29     98
Matchweek 34     94
Matchweek 35     80
Matchweek 36     80
Matchweek 37     80
Matchweek 38     80
Name: Round, dtype: int64

In [8]:
matches.dtypes

Date             object
Time             object
Comp             object
Round            object
Day              object
Venue            object
Result           object
GF              float64
GA              float64
Opponent         object
xG              float64
xGA             float64
Poss            float64
Attendance      float64
Captain          object
Formation        object
Referee          object
Match Report     object
Notes           float64
Sh              float64
SoT             float64
Dist            float64
FK              float64
PK                int64
PKatt             int64
Season            int64
Team             object
dtype: object

In [9]:
#converting date from object data type to date time data type
matches["Date"] = pd.to_datetime(matches["Date"])

In [10]:
'''converting venue from object data type to numeric, by converting it from object to category and then category to
numeric data type'''
matches["Venue_code"] = matches["Venue"].astype("category").cat.codes

In [11]:
#converting opponent from object to numeric data type in a similar way to venue
#by giving a unique code to each opponent
matches["Opp_code"] = matches["Opponent"].astype("category").cat.codes

In [12]:
#coverting time to only hours
#regex is regular expression, replacing ':' with nothing
matches["Hour"] = matches["Time"].str.replace(":.+", "", regex=True).astype("int")

In [13]:
#converting date from object to numeric by assigning unique code to each day
matches["Day_code"] = matches["Date"].dt.dayofweek

In [14]:
#this returns boolean value but after adding astype it will return a integer value
matches["Target"] = (matches["Result"] == "W").astype("int")

In [15]:
matches

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,...,FK,PK,PKatt,Season,Team,Venue_code,Opp_code,Hour,Day_code,Target
1,2023-08-12,12:30,Premier League,Matchweek 1,Sat,Home,W,2.0,1.0,Nott'ham Forest,...,0.0,0,0,2024,Arsenal,1,18,12,5,1
2,2023-08-21,20:00,Premier League,Matchweek 2,Mon,Away,W,1.0,0.0,Crystal Palace,...,0.0,1,1,2024,Arsenal,0,7,20,0,1
3,2023-08-26,15:00,Premier League,Matchweek 3,Sat,Home,D,2.0,2.0,Fulham,...,0.0,1,1,2024,Arsenal,1,9,15,5,0
4,2023-09-03,16:30,Premier League,Matchweek 4,Sun,Home,W,3.0,1.0,Manchester Utd,...,0.0,0,0,2024,Arsenal,1,15,16,6,1
5,2023-09-17,16:30,Premier League,Matchweek 5,Sun,Away,W,1.0,0.0,Everton,...,0.0,0,0,2024,Arsenal,0,8,16,6,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38,2020-07-07,18:00,Premier League,Matchweek 34,Tue,Away,L,1.0,2.0,Watford,...,1.0,0,0,2020,Norwich City,0,22,18,1,0
39,2020-07-11,12:30,Premier League,Matchweek 35,Sat,Home,L,0.0,4.0,West Ham,...,1.0,0,0,2020,Norwich City,1,24,12,5,0
40,2020-07-14,20:15,Premier League,Matchweek 36,Tue,Away,L,0.0,1.0,Chelsea,...,0.0,0,0,2020,Norwich City,0,6,20,1,0
41,2020-07-18,17:30,Premier League,Matchweek 37,Sat,Home,L,0.0,2.0,Burnley,...,0.0,0,0,2020,Norwich City,1,5,17,5,0
42,2020-07-26,16:00,Premier League,Matchweek 38,Sun,Away,L,0.0,5.0,Manchester City,...,0.0,0,0,2020,Norwich City,0,14,16,6,0

In [16]:
from sklearn.ensemble import RandomForestClassifier
#RandomForest is a type of ML model that can pick up non-linearity from a data that a linear model cannot pick

In [17]:
rf = RandomForestClassifier(n_estimators=50, min_samples_split=10, random_state=1)

In [18]:
train = matches[matches["Date"] < '2024-01-01']

In [19]:
test = matches[matches["Date"] > '2024-01-01']

In [20]:
predictors = ["Venue_code", "Opp_code", "Hour", "Day_code"]

In [21]:
rf.fit(train[predictors], train["Target"])

RandomForestClassifier(min_samples_split=10, n_estimators=50, random_state=1)

In [22]:
preds = rf.predict(test[predictors])

In [23]:
from sklearn.metrics import accuracy_score

In [24]:
acc = accuracy_score(test["Target"], preds)

In [25]:
acc

0.6557971014492754

In [26]:
combined = pd.DataFrame(dict(actual=test["Target"], predicted=preds))

In [27]:
pd.crosstab(index=combined["actual"], columns=combined["predicted"])

predicted    0   1
actual
0          146  30
1           65  35

In [28]:
from sklearn.metrics import precision_score

In [29]:
precision_score(test["Target"], preds)

0.5384615384615384

In [30]:
grouped_matches = matches.groupby("Team")

In [31]:
group = grouped_matches.get_group("Manchester City")

In [32]:
group

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,...,FK,PK,PKatt,Season,Team,Venue_code,Opp_code,Hour,Day_code,Target
1,2023-08-11,20:00,Premier League,Matchweek 1,Fri,Away,W,3.0,0.0,Burnley,...,0.0,0,0,2024,Manchester City,0,5,20,4,1
3,2023-08-19,20:00,Premier League,Matchweek 2,Sat,Home,W,1.0,0.0,Newcastle Utd,...,0.0,0,0,2024,Manchester City,1,16,20,5,1
4,2023-08-27,14:00,Premier League,Matchweek 3,Sun,Away,W,2.0,1.0,Sheffield Utd,...,2.0,0,1,2024,Manchester City,0,19,14,6,1
5,2023-09-02,15:00,Premier League,Matchweek 4,Sat,Home,W,5.0,1.0,Fulham,...,0.0,1,1,2024,Manchester City,1,9,15,5,1
6,2023-09-16,15:00,Premier League,Matchweek 5,Sat,Away,W,3.0,1.0,West Ham,...,1.0,0,0,2024,Manchester City,0,24,15,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51,2020-07-08,18:00,Premier League,Matchweek 34,Wed,Home,W,5.0,0.0,Newcastle Utd,...,1.0,0,0,2020,Manchester City,1,16,18,2,1
52,2020-07-11,20:00,Premier League,Matchweek 35,Sat,Away,W,5.0,0.0,Brighton,...,1.0,0,0,2020,Manchester City,0,4,20,5,1
53,2020-07-15,18:00,Premier League,Matchweek 36,Wed,Home,W,2.0,1.0,Bournemouth,...,1.0,0,0,2020,Manchester City,1,2,18,2,1
55,2020-07-21,18:00,Premier League,Matchweek 37,Tue,Away,W,4.0,0.0,Watford,...,1.0,0,1,2020,Manchester City,0,22,18,1,1
56,2020-07-26,16:00,Premier League,Matchweek 38,Sun,Home,W,5.0,0.0,Norwich City,...,0.0,0,0,2020,Manchester City,1,17,16,6,1

In [33]:
def rolling_averages(group, cols, new_cols):
    group = group.sort_values("Date")
    rolling_stats = group[cols].rolling(3, closed = 'left').mean()
    group[new_cols] = rolling_stats
    group = group.dropna(subset = new_cols)
    return group

In [34]:
cols = ["GF", "GA", "Sh", "SoT", "Dist", "FK", "PK", "PKatt"]
new_cols = [f"{c}_rolling" for c in cols]

In [35]:
new_cols

['GF_rolling',
 'GA_rolling',
 'Sh_rolling',
 'SoT_rolling',
 'Dist_rolling',
 'FK_rolling',
 'PK_rolling',
 'PKatt_rolling']

In [36]:
rolling_averages(group, cols, new_cols)

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,...,Day_code,Target,GF_rolling,GA_rolling,Sh_rolling,SoT_rolling,Dist_rolling,FK_rolling,PK_rolling,PKatt_rolling
4,2019-08-31,15:00,Premier League,Matchweek 4,Sat,Home,W,4.0,0.0,Brighton,...,5,1,3.333333,1.000000,20.333333,7.666667,15.633333,0.000000,0.333333,0.333333
5,2019-09-14,17:30,Premier League,Matchweek 5,Sat,Away,L,2.0,3.0,Norwich City,...,5,0,3.000000,1.000000,21.000000,7.000000,15.200000,0.333333,0.000000,0.000000
7,2019-09-21,15:00,Premier League,Matchweek 6,Sat,Home,W,8.0,0.0,Watford,...,5,1,3.000000,1.333333,19.333333,6.333333,15.100000,0.333333,0.000000,0.000000
9,2019-09-28,17:30,Premier League,Matchweek 7,Sat,Away,W,3.0,1.0,Everton,...,5,1,4.666667,1.000000,22.333333,8.000000,15.133333,1.000000,0.333333,0.333333
11,2019-10-06,14:00,Premier League,Matchweek 8,Sun,Home,L,0.0,2.0,Wolves,...,6,0,4.333333,1.333333,23.666667,8.666667,14.900000,1.000000,0.333333,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41,2024-03-10,15:45,Premier League,Matchweek 28,Sun,Away,D,1.0,1.0,Liverpool,...,6,0,1.666667,0.333333,22.333333,8.000000,16.933333,0.666667,0.000000,0.000000
43,2024-03-31,16:30,Premier League,Matchweek 30,Sun,Home,D,0.0,0.0,Arsenal,...,6,0,1.666667,0.666667,17.333333,6.666667,17.266667,0.666667,0.000000,0.000000
44,2024-04-03,20:15,Premier League,Matchweek 31,Wed,Home,W,4.0,1.0,Aston Villa,...,2,1,1.333333,0.666667,16.333333,5.000000,16.833333,0.333333,0.000000,0.000000
45,2024-04-06,12:30,Premier League,Matchweek 32,Sat,Away,W,4.0,2.0,Crystal Palace,...,5,1,1.666667,0.666667,15.666667,6.000000,16.233333,0.666667,0.000000,0.000000
47,2024-04-13,15:00,Premier League,Matchweek 33,Sat,Home,W,5.0,1.0,Luton Town,...,5,1,2.666667,1.000000,18.333333,6.666667,15.400000,0.666667,0.000000,0.000000

In [37]:
matches_rolling = matches.groupby("Team").apply(lambda x: rolling_averages(x, cols, new_cols))

In [38]:
#matches_rolling

In [39]:
matches_rolling = matches_rolling.droplevel('Team')

In [40]:
#matches_rolling

In [41]:
matches_rolling.index = range(matches_rolling.shape[0])

In [42]:
#matches_rolling

In [43]:
def make_predictions(data, predictors):
    train = data[data["Date"] < '2022-01-01']
    test = data[data["Date"] > '2022-01-01']
    rf.fit(train[predictors], train["Target"])
    preds = rf.predict(test[predictors])
    combined = pd.DataFrame(dict(actual=test["Target"], predicted=preds), index=test.index)
    error = precision_score(test["Target"], preds)
    return combined, error

In [44]:
combined, error = make_predictions(matches_rolling, predictors + new_cols)

In [45]:
error

0.5686274509803921

In [46]:
combined

      actual  predicted
93         0          1
94         1          0
95         1          0
96         1          1
97         1          1
...      ...        ...
3624       0          0
3625       0          0
3626       0          0
3627       0          0
3628       0          0

[1812 rows x 2 columns]

In [47]:
combined = combined.merge(matches_rolling[["Date", "Team", "Opponent", "Result"]], left_index=True, right_index=True)

In [48]:
combined

,actual,predicted,Date,Team,Opponent,Result
93,0,1,2022-01-23,Arsenal,Burnley,D
94,1,0,2022-02-10,Arsenal,Wolves,W
95,1,0,2022-02-19,Arsenal,Brentford,W
96,1,1,2022-02-24,Arsenal,Wolves,W
97,1,1,2022-03-06,Arsenal,Watford,W
...,...,...,...,...,...,...
3624,0,0,2024-04-02,Wolverhampton Wanderers,Burnley,D
3625,0,0,2024-04-06,Wolverhampton Wanderers,West Ham,L
3626,0,0,2024-04-13,Wolverhampton Wanderers,Nott'ham Forest,D
3627,0,0,2024-04-20,Wolverhampton Wanderers,Arsenal,L
3628,0,0,2024-04-24,Wolverhampton Wanderers,Bournemouth,L

In [49]:
class MissingDict(dict):
    __missing__=lambda self, key: key
    
map_values = {"Brighton and Hove Albion": "Brighton", "Manchester United": "Manchester Utd",
              "Newcastle United": "Newcastle Utd", "Tottenham Hotspur": "Tottenham", "West Ham United": "West Ham",
              "Wolverhampton Wanderers": "Wolves"} 
mapping = MissingDict(**map_values)

In [50]:
mapping["West Ham United"]

'West Ham'

In [51]:
combined["New_Team"] = combined["Team"].map(mapping)

In [52]:
combined

,actual,predicted,Date,Team,Opponent,Result,New_Team
93,0,1,2022-01-23,Arsenal,Burnley,D,Arsenal
94,1,0,2022-02-10,Arsenal,Wolves,W,Arsenal
95,1,0,2022-02-19,Arsenal,Brentford,W,Arsenal
96,1,1,2022-02-24,Arsenal,Wolves,W,Arsenal
97,1,1,2022-03-06,Arsenal,Watford,W,Arsenal
...,...,...,...,...,...,...,...
3624,0,0,2024-04-02,Wolverhampton Wanderers,Burnley,D,Wolves
3625,0,0,2024-04-06,Wolverhampton Wanderers,West Ham,L,Wolves
3626,0,0,2024-04-13,Wolverhampton Wanderers,Nott'ham Forest,D,Wolves
3627,0,0,2024-04-20,Wolverhampton Wanderers,Arsenal,L,Wolves
3628,0,0,2024-04-24,Wolverhampton Wanderers,Bournemouth,L,Wolves

In [53]:
merged = combined.merge(combined, left_on=["Date", "New_Team"], right_on=["Date", "Opponent"])

In [54]:
merged

,actual_x,predicted_x,Date,Team_x,Opponent_x,Result_x,New_Team_x,actual_y,predicted_y,Team_y,Opponent_y,Result_y,New_Team_y
0,0,1,2022-01-23,Arsenal,Burnley,D,Arsenal,0,0,Burnley,Arsenal,D,Burnley
1,1,0,2022-02-10,Arsenal,Wolves,W,Arsenal,0,0,Wolverhampton Wanderers,Arsenal,L,Wolves
2,1,0,2022-02-19,Arsenal,Brentford,W,Arsenal,0,0,Brentford,Arsenal,L,Brentford
3,1,1,2022-02-24,Arsenal,Wolves,W,Arsenal,0,0,Wolverhampton Wanderers,Arsenal,L,Wolves
4,1,1,2022-03-06,Arsenal,Watford,W,Arsenal,0,0,Watford,Arsenal,L,Watford
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1698,0,0,2024-04-02,Wolverhampton Wanderers,Burnley,D,Wolves,0,1,Burnley,Wolves,D,Burnley
1699,0,0,2024-04-06,Wolverhampton Wanderers,West Ham,L,Wolves,1,0,West Ham United,Wolves,W,West Ham
1700,0,0,2024-04-13,Wolverhampton Wanderers,Nott'ham Forest,D,Wolves,0,0,Nottingham Forest,Wolves,D,Nottingham Forest
1701,0,0,2024-04-20,Wolverhampton Wanderers,Arsenal,L,Wolves,1,0,Arsenal,Wolves,W,Arsenal
1702,0,0,2024-04-24,Wolverhampton Wanderers,Bournemouth,L,Wolves,1,0,Bournemouth,Wolves,W,Bournemouth

In [55]:
merged[(merged["predicted_x"] ==1) & (merged["predicted_y"] ==0)]["actual_x"].value_counts()

1    206
0    140
Name: actual_x, dtype: int64